on:
  push:
    branches:
      - master
  pull_request:
name: ci
jobs:
  director:
    runs-on: ubuntu-latest
    outputs:
      scopes: ${{ steps.interrogate.outputs.scopes }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - id: interrogate
        run: node ./.github/workflows/interrogate.js
  test:
    runs-on: ubuntu-latest
    needs: director
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.director.outputs.scopes.nodePaths)}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: echo ./packages/${{ matrix.package }}
      - run: cd ./packages/${{ matrix.package }}
      - run: npm install
        working-directory: ./packages/${{ matrix.package }}
      - run: pwd
      - run: npm test
        working-directory: ./packages/${{ matrix.package }}
      - run: npm run lint
        working-directory: ./packages/${{ matrix.package }}
  go-test:
    name: Go tests
    runs-on: ubuntu-latest
    needs: director
    strategy:
      fail-fast: false
      matrix:
        module: ${{fromJson(needs.director.outputs.scopes.goPaths)}}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.14'
    - name: Install goimports
      run: go get golang.org/x/tools/cmd/goimports
    - name: Checkout code
      uses: actions/checkout@v2
    - name: goimports
      run: |
        test -z "$($(go env GOPATH)/bin/goimports -l .)"
      working-directory: ./${{ matrix.module }}
    - name: Instructions to fix goimports (if necessary)
      run: echo Run goimports -w .
      if: failure()
    - run: go test ./...
      working-directory: ./${{ matrix.module }}
  bash-test:
    name: Bash tests
    runs-on: ubuntu-latest
    needs: director
    strategy:
      fail-fast: false
      matrix:
        module: ${{fromJson(needs.director.outputs.scopes.bashPaths)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: bashtest
        run: |
          ./test.sh
        working-directory: ./${{ matrix.module }}
